### ISSUE TITLE
Indexing Owner

### ISSUE THREAD

**Issue by tofutim** [adrianhall/dotnetconf#1]
Thanks for putting this out there. It was helpful to get an idea of how to integrate auth and the TodoItems. I did have a question though. Since you are now filtering results by Owner, it should probably be indexed. How can this be achieved?

**Comment by adrianhall** [comment]
It's a standard Entity Framework application from that respect.   I'd recommend reviewing http://www.entityframeworktutorial.net/code-first/entity-framework-code-first.aspx to get a handle on EF Code First.
